language: c
sudo: required
dist: trusty

env:
- CFLAGS=-Wno-absolute-value -Werror

compiler:
  - gcc
  - clang

cache:
  directories:
    - $HOME/srb2_cache

addons:
  apt:
    packages:
    - libsdl2-mixer-dev
    - libpng-dev
    - libgl1-mesa-dev
    - libgme-dev
    - p7zip-full

before_script:
  - mkdir $HOME/srb2_cache
  - wget http://rosenthalcastle.org/srb2/SRB2-v2114-Installer.exe -c -O $HOME/srb2_cache/SRB2-v2114-Installer.exe
  - 7z x $HOME/srb2_cache/SRB2-v2114-Installer.exe -oassets
  - mkdir build
  - cd build
  - cmake ..

script: make
